import type { DB, SQLValue } from "../../../shared/persistence.js";
export function customerQuery1(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT * FROM attribution_stores WHERE id=? AND merchant_id=?").get(...values); }
export function customerQuery2(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT * FROM attribution_sources WHERE code=?").get(...values); }
export function customerQuery3(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT * FROM offline_records WHERE merchant_id=? AND store_id=? AND kind=? AND external_id=? ORDER BY revision DESC LIMIT 1").get(...values); }
export function customerQuery4(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT code FROM attribution_sources WHERE code=? AND room_id=? AND disabled_at IS NULL AND created_at<=?").get(...values); }
export function customerQuery5(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT id,name FROM attribution_stores WHERE merchant_id=? ORDER BY created_at,id").all(...values); }
export function customerQuery6(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT code FROM attribution_sources WHERE store_id=?").all(...values); }
export function customerQuery7(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT coalesce(sum(kind='visit'),0) AS visits,coalesce(sum(kind='order'),0) AS orders,coalesce(sum(CASE WHEN kind='order' THEN amount_cents ELSE 0 END),0) AS salesCents,coalesce(sum(CASE WHEN kind='cost' THEN amount_cents ELSE 0 END),0) AS costCents,coalesce(sum(linked_source_code IS NULL),0) AS unlinkedRecords,coalesce(sum(CASE WHEN kind='order' AND linked_source_code IS NULL THEN amount_cents ELSE 0 END),0) AS unlinkedSalesCents FROM offline_records r WHERE merchant_id=? AND store_id=? AND voided=0 AND NOT EXISTS (SELECT 1 FROM offline_records newer WHERE newer.merchant_id=r.merchant_id AND newer.store_id=r.store_id AND newer.kind=r.kind AND newer.external_id=r.external_id AND newer.revision>r.revision)").get(...values); }
export function customerQuery8(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT id,name,external_ref AS externalRef,created_at AS createdAt FROM attribution_stores WHERE merchant_id=? ORDER BY created_at,id").all(...values); }
export function customerQuery9(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT id FROM attribution_stores WHERE merchant_id=? AND external_ref=?").get(...values); }
export function customerQuery10(db: DB, ...values: SQLValue[]) { return db.prepare("INSERT INTO attribution_stores VALUES(?,?,?,?,?)").run(...values); }
export function customerQuery11(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT code,store_id AS storeId,room_id AS roomId,label,created_at AS createdAt,disabled_at AS disabledAt FROM attribution_sources WHERE store_id=? ORDER BY created_at DESC,code").all(...values); }
export function customerQuery12(db: DB, ...values: SQLValue[]) { return db.prepare("INSERT INTO attribution_sources VALUES(?,?,?,?,?,NULL)").run(...values); }
export function customerQuery13(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT store_id FROM attribution_sources WHERE code=?").get(...values); }
export function customerQuery14(db: DB, ...values: SQLValue[]) { return db.prepare("UPDATE attribution_sources SET disabled_at=coalesce(disabled_at,?) WHERE code=?").run(...values); }
export function customerQuery15(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT request_hash,receipt_json FROM offline_batches WHERE merchant_id=? AND idempotency_key=?").get(...values); }
export function customerQuery16(db: DB, ...values: SQLValue[]) { return db.prepare("INSERT INTO offline_batches VALUES(?,?,?,?,?,?,?,?,?)").run(...values); }
export function customerQuery17(db: DB, ...values: SQLValue[]) { return db.prepare("INSERT INTO offline_records VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(...values); }
export function customerQuery18(db: DB, ...values: SQLValue[]) { return db.prepare(`SELECT r.rowid AS cursor,r.id,r.store_id AS storeId,r.kind,r.external_id AS externalId,r.revision,r.source_code AS sourceCode,r.linked_source_code AS linkedSourceCode,r.match_state AS matchState,r.customer_ref AS customerRef,r.occurred_at AS occurredAt,r.amount_cents AS amountCents,r.voided,r.note,r.actor_id AS actorId,r.created_at AS createdAt,r.batch_id AS batchId FROM offline_records r WHERE r.merchant_id=? AND r.store_id=? AND r.rowid<? AND NOT EXISTS (SELECT 1 FROM offline_records newer WHERE newer.merchant_id=r.merchant_id AND newer.store_id=r.store_id AND newer.kind=r.kind AND newer.external_id=r.external_id AND newer.revision>r.revision) ORDER BY r.rowid DESC LIMIT 101`).all(...values); }
export function customerQuery19(db: DB, ...values: SQLValue[]) { return db.prepare("SELECT * FROM offline_records WHERE id=? AND merchant_id=?").get(...values); }
export function customerQuery20(db: DB, ...values: SQLValue[]) { return db.prepare(`SELECT r.id,r.store_id AS storeId,r.kind,r.external_id AS externalId,r.revision,r.source_code AS sourceCode,r.linked_source_code AS linkedSourceCode,r.match_state AS matchState,r.customer_ref AS customerRef,r.occurred_at AS occurredAt,r.amount_cents AS amountCents,r.voided,r.note,r.actor_id AS actorId,r.created_at AS createdAt,r.batch_id AS batchId FROM offline_records r WHERE merchant_id=? AND store_id=? AND kind=? AND external_id=? ORDER BY revision DESC`).all(...values); }
